# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8dd15efd794258f7f2eedaff6626f937"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "test-udeshya"
handle = "test-udeshya"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "checkout-functions-test.myshopify.com"
